language: csharp
sudo: required
mono: none
dotnet: 2.2
dist: xenial
script:
  - dotnet restore
  - dotnet build
  - dotnet test ./Core.Tests/
  - dotnet test ./Data.Tests/
  - dotnet test ./Http.Tests/
  - dotnet test ./MediaServer.Core.Tests/
  - dotnet test ./MediaServer.Plex.Tests/
  - dotnet test ./Security.OAuth.Tests/
  - dotnet pack ./Core/Core.csproj /p:NuspecFile=./FrostAura.Libraries.Core.nuspec --version-suffix "$TRAVIS_BUILD_NUMBER" --output "$TRAVIS_BUILD_DIR" --configuration Release
deploy:
  skip_cleanup: true
  provider: script
  script: cd $TRAVIS_BUILD_DIR & ls & dotnet nuget push "$TRAVIS_BUILD_DIR/*.nupkg" -k $NUGET_API_KEY -s $NUGET_SOURCE
  on:
    branch: master
